# Generated by Django 6.1.1 on 2026-09-15 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='product',
            new_name='products_pr_sku_ca0cdc_idx',
            old_name='products_pr_sku_5d9a9e_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='products_pr_categor_d726ba_idx',
            old_name='products_pr_categor_9e8d9b_idx',
        ),
    ]
